In [1]:
import pandas as pd
import numpy as np
import cesium as cs

# Load train curves
train = pd.read_csv('data/training_set.csv')

In [2]:
train.head()

   object_id         mjd  passband        flux   flux_err  detected
0        615  59750.4229         2 -544.810303   3.622952         1
1        615  59750.4306         1 -816.434326   5.553370         1
2        615  59750.4383         3 -471.385529   3.801213         1
3        615  59750.4450         4 -388.984985  11.395031         1
4        615  59752.4070         2 -681.858887   4.041204         1

In [6]:
tss = train.groupby(['object_id', 'passband'])

In [7]:
ts = tss.get_group((615, 2))
ts.head()

    object_id         mjd  passband        flux  flux_err  detected
0         615  59750.4229         2 -544.810303  3.622952         1
4         615  59752.4070         2 -681.858887  4.041204         1
9         615  59767.2968         2 -548.013550  3.462291         1
14        615  59770.2179         2 -554.903198  3.927843         1
19        615  59779.3188         2 -630.523682  4.333287         1

In [16]:
from cesium.time_series import TimeSeries
from cesium.featurize import featurize_single_ts

demo_series = TimeSeries(
    t = ts['mjd'],
    m = ts['flux'],
    e = ts['flux_err'],
)
feat_list = [
    'amplitude',
    'flux_percentile_ratio_mid20',
    'flux_percentile_ratio_mid35',
    'flux_percentile_ratio_mid50',
    'flux_percentile_ratio_mid65',
    'flux_percentile_ratio_mid80',
    'max_slope',
    'maximum',
    'median',
    'median_absolute_deviation',
    'minimum',
    'percent_amplitude',
    'percent_beyond_1_std',
    'percent_close_to_median',
    'percent_difference_flux_percentile',
    'period_fast',
    'qso_log_chi2_qsonu',
    'qso_log_chi2nuNULL_chi2nu',
    'skew',
    'std',
    'stetson_j',
    'stetson_k',
    'weighted_average',
]
featurize_single_ts(demo_series, feat_list)

feature                             channel
amplitude                           0           6.469217e+02
flux_percentile_ratio_mid20         0          8.335577e-109
flux_percentile_ratio_mid35         0           5.680106e-71
flux_percentile_ratio_mid50         0           2.914884e-49
flux_percentile_ratio_mid65         0           6.719411e-20
flux_percentile_ratio_mid80         0           3.634994e-06
max_slope                           0           4.233611e+02
maximum                             0           6.119846e+02
median                              0          -2.656860e+02
median_absolute_deviation           0           3.681285e+02
minimum                             0          -6.818589e+02
percent_amplitude                   0          1.446016e+163
percent_beyond_1_std                0           5.689655e-01
percent_close_to_median             0           1.724138e-01
percent_difference_flux_percentile  0          1.679215e+161
period_fast                         0           3.489429e+02
qso_log_chi2_qsonu                  0           9.664463e+00
qso_log_chi2nuNULL_chi2nu           0           2.338821e-01
skew                                0           3.310635e-01
std                                 0           4.511808e+02
stetson_j                           0           4.007530e+03
stetson_k                           0           1.053491e+00
weighted_average                    0          -1.022206e+02
dtype: float64